/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ntut_tof_falldetection_TOFManager */

#ifndef _Included_com_ntut_tof_falldetection_TOFManager
#define _Included_com_ntut_tof_falldetection_TOFManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ntut_tof_falldetection_TOFManager
 * Method:    startDevice
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ntut_tof_falldetection_TOFManager_startDevice
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
